use TopBrains;

--adding the constraints in Zipcode_info

select * from ZIPCODE_INFO;


EXEC sp_help 'ZIPCODE_INFO';

ALTER TABLE ZIPCODE_INFO
ALTER COLUMN ZIP_CODE Varchar(5) NOT NULL;

ALTER Table ZIPCODE_INFO
ADD Constraint ZIP_PK PRIMARY KEY (ZIP_CODE);

ALTER Table ZIPCODE_INFO
ALTER COLUMN CITY Varchar(25) NOT NULL;

ALTER Table ZIPCODE_INFO
ALTER COLUMN STATE Varchar(2) NOT NULL;


--contstraints in instructir_info
Select * from INSTRUCTOR_INFO;

ALTER Table INSTRUCTOR_INFO
ALTER COLUMN INSTRUCTOR_ID Varchar(8) NOT NULL;

ALTER Table INSTRUCTOR_INFO
ALTER COLUMN INSTRUCTOR_FIRST_NAME Varchar(25) NOT NULL;

ALTER Table INSTRUCTOR_INFO
ALTER COLUMN INSTRUCTOR_LAST_NAME Varchar(25) NOT NULL;

ALTER Table INSTRUCTOR_INFO
ADD Constraint INSTRUCTOR_ID_PK PRIMARY KEY (INSTRUCTOR_ID);

ALTER TABLE INSTRUCTOR_INFO
ADD Constraint ZIP_INSTRUCTOR_FK Foreign Key (ZIP_CODE)
References ZIPCODE_INFO(ZIP_CODE);

--altering in course_info

ALTER Table COURSE_INFO
ALTER COLUMN COURSE_NO Numeric(8) NOT NULL;

ALTER Table COURSE_INFO
ALTER COLUMN COURSE_NAME Varchar(50) NOT NULL;

ALTER Table COURSE_INFO
ALTER COLUMN COST Numeric(9) NOT NULL;

ALTER Table COURSE_INFO
ADD CONSTRAINT COURSE_NO_PK Primary Key(COURSE_NO);

--altering the student-info

ALTER Table STUDENT_INFO
ALTER COLUMN STUDENT_ID Numeric(8) NOT NULL;

ALTER Table STUDENT_INFO
ALTER COLUMN STUDENT_FIRST_NAME Varchar(25) NOT NULL;

ALTER Table STUDENT_INFO
ALTER COLUMN STUDENT_LAST_NAME Varchar(25) NOT NULL;

ALTER TABLE STUDENT_INFO
ADD Constraint STUDENT_ID_PK Primary Key (STUDENT_ID);

ALTER TABLE STUDENT_INFO
ADD Constraint ZIP_STUDENT_FK Foreign Key (ZIP_CODE) References ZIPCODE_INFO(ZIP_CODE);

--altering the section_info
ALTER Table SECTION_INFO
ALTER COLUMN SECTION_ID Numeric(8) NOT NULL;

ALTER Table SECTION_INFO
ALTER COLUMN INSTRUCTOR_ID Numeric(8) NOT NULL;

ALTER Table SECTION_INFO
ALTER COLUMN SECTION_NO Numeric(3) NOT NULL;

ALTER Table SECTION_INFO
ADD Constraint SECTION_ID_PK Primary Key(SECTION_ID);

ALTER Table SECTION_INFO
ADD Constraint COURSE_SECTION_FK Foreign Key(COURSE_NO) references COURSE_INFO(COURSE_NO);

EXEC sp_help 'SECTION_INFO';